name: AlvaSvoboda
favicon: null
layout_spectrum: 0.4867234753910452
typography_spectrum: 0.8361147246323526
title: 'Games, Management and the Fate of the Universe'
description: Market Simulation Games
navigation:
  - name: Aljo Svoboda
    url: 'http://www.aljosvoboda.com'
    type: external
  - name: Svobius -- an as-yet nonexistent indie game development company
    url: 'http://svobi.us'
    type: external
  - name: >-
      MarketSimulationGames -- an as-yet nonexistent company disrupting at the
      nexus of markets, simulations, and g-g-g-games
    url: 'http://marketsimulationgames.com'
    type: external
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15f10a'
    - '#81453d'
    - '#d7d50a'
    - '#1310dd'
    - '#fb99fd'
  brandStrength: 0.2887027049437165
  lightness: 0.5804252040106803
  saturation: 0.9821990591008216
  rhythmicContrast: 0.7743984195403755
purpose: []
