typography_spectrum: 0.8361147246323526
color:
  brandColors:
    - '#c8a85d'
    - '#1b1a18'
    - '#655b3c'
    - '#f3e293'
    - '#e0412c'
  brandStrength: 0.2887027049437165
  lightness: 0.5804252040106803
  saturation: 0.9821990591008216
  rhythmicContrast: 0.7743984195403755
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4867234753910452
analytics:
  google: null
  facebook: null
  twitter: null
name: AlvaSvoboda
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Aljo Svoboda
    url: 'http://www.aljosvoboda.com'
    type: external
  - name: Svobius -- an as-yet nonexistent indie game development company
    url: 'http://svobi.us'
    type: external
favicon: null
title: 'Games, Management and the Fate of the Universe'
description: Market Simulation Games
purpose: []
